version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                command: npm test --reporter mocha-junit-reporter
                environment:
                  MOCHA_FILE: test-results/mocha/results.xml
            - store_test_results:
                path: test-results/mocha
            - store_artifacts:
                path: test-results/mocha
workflows:
    build-and-test:
      jobs:
        - build-and-test
